version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:15"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
      include: scope
