// Autogenerated by github.com/snonky/pocketbase-gogen.
// Please feel free to edit after noting the explanation:
//
// This file is an intermediate product of the proxy generation.
// It is called a 'schema as code' or just 'template'. It is not meant to be
// compiled it is only meant for human interaction, place it in a separate package
// but never import it.
// Here's what you can do to influence the final code generation step:
//
// Do:
//   - Edit the struct names. The names are directly copied to the proxy struct definitions.
//   - Remove structs or fields that you don't want in the generated code. Note that upon removing a struct
//     you also have to remove any fields that have that struct as their type.
//   - Edit the type name in the '// select:' comments.
//   - Change the const names of the select options by adding alias lines (// >) to the select options list.
//     Example:
//     // select: MySelectType
//     // - optionA
//     // > aliasA
//     // - v2.0
//     // > v2_0
//   - Edit the field names. If you do, the generator still needs to know the original database field name.
//     To provide this, add a '// schema-name: [original field name]' comment directly above the field.
//   - Add methods to the template structs. The generator will replace any fields you access with the also
//     generated getters/setters. Be aware of that when repeatedly assigning a template field. You are
//     calling a setter on every assignment. The methods can also call each other.
//
// Do not:
//   - Add structs that do not represent a PB collection.
//   - Add fields that are not part of the PB schema to the structs.
//   - Change the '// collection-name:' comments unless the collection was actually renamed.
//     If the comment is missing from the first struct field, the generator will print a warning.
//   - Change the select values in the () of the '// select:' comments'
//   - Remove the '// system:' doc comments from the system fields. Generation will fail if you do so.
//   - Shadow any names from the core.Record struct. Generation will also fail for safety.
//   - Rename fields without preserving the original name with a '// schema-name:' comment.'
//
// If you edit this file, be careful and back it up to prevent the changes from being overridden by
// subsequent runs of the template command. Check out the PocketBase docs to find out how to use the
// generated code in your code: https://pocketbase.io/docs/go-record-proxy/
package pbschema

import "github.com/pocketbase/pocketbase/tools/types"

type Users struct {
	// collection-name: users
	// system: id
	Id string
	// system: password
	password string
	// system: tokenKey
	tokenKey string
	// system: email
	email string
	// system: emailVisibility
	emailVisibility bool
	// system: verified
	verified bool
	name     string
	avatar   string
	created  types.DateTime
	updated  types.DateTime
}

type Families struct {
	// collection-name: families
	// system: id
	Id          string
	name        string
	invite_code string
	created     types.DateTime
	updated     types.DateTime
}

type FamilyMembers struct {
	// collection-name: family_members
	// system: id
	Id        string
	family_id *Families
	user_id   *Users
	// select: RoleSelectType
	// - owner
	// - member
	role    int
	created types.DateTime
	updated types.DateTime
}

type Categories struct {
	// collection-name: categories
	// system: id
	Id         string
	family_id  *Families
	name       string
	icon       string
	color      string
	is_default bool
	// select: TypeSelectType
	// - expense
	// - income
	type_     int
	is_master bool
	created   types.DateTime
	updated   types.DateTime
}

type Transactions struct {
	// collection-name: transactions
	// system: id
	Id          string
	family_id   *Families
	created_by  *Users
	category_id *Categories
	amount      float64
	note        string
	date        types.DateTime
	// select: TypeSelectType
	// - income
	// - expense
	type_   int
	created types.DateTime
	updated types.DateTime
}

type File struct {
	// collection-name: file
	// system: id
	Id      string
	title   string
	fileku  string
	created types.DateTime
	updated types.DateTime
}

type Jenis struct {
	// collection-name: jenis
	// system: id
	Id string
	// select: JenisSelectType
	// - system
	// - manual
	jenis int
}

type DigiflazzCredentials struct {
	// collection-name: digiflazz_credentials
	// system: id
	Id                 string
	family_id          *Families
	username           string
	api_key            string
	testing            bool
	webhook_id         string
	webhook_token_hash string
	webhook_secret     string
	is_active          bool
	created            types.DateTime
	updated            types.DateTime
}

type DigiflazzProducts struct {
	// collection-name: digiflazz_products
	// system: id
	Id                    string
	family_id             *Families
	credential_id         *DigiflazzCredentials
	product_name          string
	category              string
	brand                 string
	type_                 string
	buyer_sku_code        string
	price                 float64
	admin                 float64
	buyer_product_status  string
	seller_product_status string
	stock                 float64
	multi                 bool
	desc                  string
	provider              string
	is_prepaid            bool
	created               types.DateTime
	updated               types.DateTime
}

type DigiflazzOrders struct {
	// collection-name: digiflazz_orders
	// system: id
	Id             string
	family_id      *Families
	created_by     *Users
	ref_id         string
	buyer_sku_code string
	customer_no    string
	product_name   string
	category       string
	// select: StatusSelectType
	// - inquiry
	// - pending
	// - processing
	// - success
	// - failed
	// - cancelled
	status         int
	price          float64
	admin          float64
	total          float64
	sn             string
	message        string
	rc             string
	payload        string
	response       string
	transaction_id string
	is_prepaid     bool
	created        types.DateTime
	updated        types.DateTime
}

type DigiflazzEvents struct {
	// collection-name: digiflazz_events
	// system: id
	Id       string
	order_id *DigiflazzOrders
	// select: EventTypeSelectType
	// - topup
	// - inquiry
	// - pay
	// - status
	// - deposit
	// - webhook
	// - error
	event_type    int
	status_before string
	status_after  string
	payload       string
	response      string
	source        string
	created       types.DateTime
	updated       types.DateTime
}
